name: Update follow-along branch
on:
  push:
    branches: [master]
  pull_request:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check it out 
        uses: actions/checkout@v2
      - name: Update the thing
        run: |
          ./scripts/resetSolutions.sh
          ./scripts/removeAnchors.sh
          git add --all
          git commit --message "Some really sweet message here"
          git push origin HEAD:follow-along
